---
title: "Guide de description d'une expérimentation en vigne"
author : Delpuech, Xavier
contributor: Dumas, Vincent;Cahurel, Jean-Yves;Gontier, Laure;Claverie, Marion;Charleroy, Arnaud
date: 2023-02-15
date-modified: 2023-02-15
bibliography: references.bib
format: html
prefer-html: true
editor: visual
---

```{r load_data}
#| echo: false
#| warning: false

library(readxl)
schema <- readxl::read_xlsx("experimental_context_description.xlsx")
thesaurus <- readxl::read_xlsx("grapevine_experimental_thesaurus.xlsx")

```

Dans un objectif de faciliter le partage et l'interopérabilité des données expérimentales dans la filière viticole

## Les champs descriptifs d'une expérimentation

Une expérimentation est décrite par les champs suivants.

```{r}
#| echo: false
#| warning: false
#| label: tbl-metadata_expe
#| tbl-cap: Metadonnées descriptives de l'expérimentation

library(dplyr)
library(kableExtra)

metadata_expe <- schema %>%
  filter(subcontext=="experimentation") %>%
  select(label_fr,description_fr,example_fr,type, enum)

kbl(metadata_expe) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))


```

## Les champs descriptifs d'une parcelle expérimentale

Les champs descriptifs d'une parcelle expérimentale sont:

```{r}
#| echo: false
#| warning: false
#| label: tbl-metadata_plot
#| tbl-cap: Metadonnées descriptives de la parcelle expérimentale

library(dplyr)
library(kableExtra)

metadata_plot <- schema %>%
  filter(subcontext=="plot") %>%
  mutate(liste=enum) %>%
  mutate(liste=gsub(x=enum,pattern=",",replacement=", ")) %>%
  #mutate(liste=linebreak(liste)) %>%
  select(label_fr,description_fr,example_fr,type, liste)


kbl(metadata_plot,escape=F) %>%
   kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

## Glossaire

```{r}
#| echo: false
#| warning: false

glossary <- thesaurus %>%
  select(terme_fr,definition_fr)

kbl(glossary) %>%
   kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```
