---
title: "Thesaurus vigne & vin"
author: 
  - name: Xavier Delpuech
    corresponding: true
    orcid: 0000-0001-7278-3209
    email: xavier.delpuech@vignevin.com
    affiliations:
      - ref: ifv
  - name: Vincent Dumas
    affiliations:
      - ref: inrae
  - name: Jean-Yves Cahurel
    affiliations:
      - ref: ifv
  - name: Laure Gontier
    affiliations:
      - ref: ifv
  - name: Marion Claverie
    affiliations:
      - ref: ifv
  - name: Arnaud Charleroy
    affiliations:
      - ref: inrae
  - name: Viviane Bécart
    affiliations:
      - ref: sgvrcdr
  - name: Romain Lacroix
    affiliations:
      - ref: sgvrcdr
  - name: Eric Duchêne
    affiliations:
      - ref: inrae
  - name: Nathalie Ollat
    affiliations:
      - ref: inrae
  - name: Joseph Tran
    affiliations:
      - ref: inrae    
  
affiliations:
  - id: ifv
    name: Institut Français de la Vigne et du Vin
  - id: inrae
    name: INRAE
  - id: sgvrcdr
    name: Syndicat Général des Vignerons Réunis des Côtes du Rhône
date: 2023-02-16
date-modified: 2023-02-15
bibliography: references.bib
format: html
prefer-html: true
editor: visual
filters: 
  - authors-block
---

## Introduction

Ce document a pour objectif de définir certains termes utilisés par la communauté scientifique et technique vigne et vin pour faciliter le partage et la compréhension mutuelle.

```{r load_data}
#| echo: false
#| warning: false

library(readxl)
thesaurus <- readxl::read_xlsx("grapevine_experimental_thesaurus.xlsx")
```

## Termes génériques

```{r}
#| echo: false
#| warning: false
#| label: tbl-generic
#| tbl-cap: Termes génériques utilisés dans un contexte expérimental

library(dplyr)
library(kableExtra)
glossary <- thesaurus %>%
  filter(contexte_fr=="générique") %>%
  select(terme_fr,definition_fr)

kbl(glossary) %>%
   kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

## Termes au vignoble

```{r}
#| echo: false
#| warning: false
#| label: tbl-vignoble
#| tbl-cap: Termes génériques utilisés sur le vignoble


glossary <- thesaurus %>%
  filter(contexte_fr=="vignoble") %>%
  select(terme_fr,definition_fr)

kbl(glossary) %>%
   kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```
